### ISSUE TITLE
filter out inactive users in the network

### ISSUE THREAD

**Issue by TheRakeshPurohit** [shirouzu/ipmsg#4]
i am using IP Messenger For Win version 4.99r11 on windows 10. How to filter out inactive members of my network.

**Comment by shirouzu** [comment]
Support BBS is here.
[](https://groups.google.com/forum/#!forum/ipmsg-bbs-eng)

**Comment by shirouzu** [comment]
Support BBS is here.
https://groups.google.com/forum/#!forum/ipmsg-bbs-eng
